// TODO REMOVE PROPER AMOUNT FROM ACCOUNT BALANCE (RUNS ONCE PER DAY)

// GET ALL ADMNIS

// COUNT USERS FOR ADMIN

// CHECK IF THEY ARE BEING CHARGED (TRIAL PERIOD)

// REMOVE APPROPRIATE AMOUNT (users / days in month)

// IF NOT ENOUGH MONEY ( balance < -$1 ), SUSPEND ADMIN/VIEW ACCOUNTS